In [271]:
conda install pandas==0.24.2

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda/envs/Python3

  added / updated specs:
    - pandas==0.24.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py36_0         153 KB
    ------------------------------------------------------------
                                           Total:         153 KB

The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2019.11.~ --> pkgs/main::ca-certificates-2020.1.1-0
  openssl            conda-forge::openssl-1.1.1d-h516909a_0 --> pkgs/main::openssl-1.1.1d-h7b6447c_4

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                       conda-forge --> pkgs/main
  pandas             conda-forge::pandas-0.24.2-py36hb3f55~ --> pkgs/main::pandas-0.24.2-py36he6710b0_0



Downloading and Extracting Packages
certifi-2019.11.28   | 153 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [272]:
conda upgrade --all -y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda/envs/Python3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libprotobuf-3.11.4         |       hd408876_0         2.9 MB
    ninja-1.9.0                |   py36hfd86e86_0         1.2 MB
    protobuf-3.11.4            |   py36he6710b0_0         635 KB
    tqdm-4.42.1                |             py_0          56 KB
    ------------------------------------------------------------
                                           Total:         4.8 MB

The following packages will be UPDATED:

  libprotobuf        conda-forge::libprotobuf-3.11.3-h8b12~ --> pkgs/main::libprotobuf-3.11.4-hd408876_0
  protobuf           conda-forge::protobuf-3.11.3-py36he1b~ --> pkgs/main::protobuf-3.11.4-py36he6710b0_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ninja                conda-forge::ninja-1.10.0-hc9558a2_0 --> pkgs/main::ninja-1.9.0-py36hfd86e86_0
  tqdm                        conda-forge::tqdm-4.43.0-py_0 --> pkgs/main::tqdm-4.42.1-py_0



Downloading and Extracting Packages
tqdm-4.42.1          | 56 KB     | ##################################### | 100%
protobuf-3.11.4      | 635 KB    | ##################################### | 100%
libprotobuf-3.11.4   | 2.9 MB    | ##################################### | 100%
ninja-1.9.0          | 1.2 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [273]:
conda install snorkel==0.9.0 -c conda-forge

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda/envs/Python3

  added / updated specs:
    - snorkel==0.9.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py36_0         149 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         149 KB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-h7b6447c_4 --> conda-forge::openssl-1.1.1d-h516909a_0



Downloading and Extracting Packages
certifi-2019.11.28   | 149 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [274]:
conda install -c conda-forge textblob

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [275]:
from snorkel.labeling import LFAnalysis
from snorkel.labeling import labeling_function
from snorkel.labeling import PandasLFApplier,LabelModel
from snorkel.preprocess import preprocessor
import nltk
from itertools import repeat
from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
import pandas as pd
import re
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

import warnings
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/faculty/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [276]:
development_split = pd.read_csv('/project/development_split.csv')
development_split

      Unnamed: 0                                             Review  Freshness
0          21310  Even more so than with the other Lecter movies...          0
1         380885   It's a delicious appetizer but you'll crave m...          1
2           5069  'Rim of the World' is a fun adventure flick fi...          1
3           5319  Again, I applaud the effort, but there's reall...          0
4           9369  Might be the least-sexy film about a hedonist ...          0
5           5519  ...the obvious passion poured into the film ma...          1
6           1848  Put indelicately via double entendre: The Deat...          1
7          66810   There needs to be a place for teen melodrama....          1
8           8737  Riveting entertainment thanks to its three lea...          1
9           4311             [T]his is undeniably great filmmaking.          1
10         36309  Chicken Run isn't just chock-full of reference...          1
11          4227  Yet another adult comedy that's heavy with rau...          1
12          1101  Netflix's Bikram documentary gets even more di...          1
13          4906  Finishing with a fine flourish makes this slow...          1
14         41866  Sure, it has its precious moments -- but Hitch...          1
15          4399  Dumbo is a lot of work by a lot of talented pe...          1
16         60278   Flunks its most crucial test: the need to pro...          0
17         10565  This is an ugly film. And the only thing uglie...          0
18        104588   It has all the ingredients for cult immortali...          1
19        110215   Distorted leaves viewers with a disjointed, u...          0
20          9874  At no point did I feel like I was at Woodstock...          0
21        315392   Ferrara gives a nice flow to this far-from-ni...          1
22          5151  It's difficult to watch a film that doesn't st...          1
23         54282  Call me. I'll see it again with you this weekend.          1
24         32695  The characters are fully dimensional, the perf...          1
25        344514   The Oscar-nominated documentary 20 Feet From ...          1
26        209612         There is nothing more to say, except 'Go.'          1
27          9812  It's hair that matters most here, and it's hai...          0
28        131147   A very subtle and smooth film. Basically a Eu...          1
29          1087  While it has some good elements and can be fun...          0
...          ...                                                ...        ...
1970        2842  A surfeit of plot succeeds only in confusing t...          0
1971       55989   It's so knowingly cute that most of its jokes...          0
1972       37492  The film succeeds as a deeply involving study ...          1
1973        2841  As far as you can work out, the film isn't aim...          0
1974       22361  A sucker-punching tour de force of offensiveness.          0
1975        1676  In making Briggman less indecisive about the c...          0
1976        5197  Putting the middle finger to originality, narr...          1
1977      390850   L.A. Confidential understands that men don't ...          1
1978       42626  Ignoring the weak storyline entirely, Rango is...          1
1979        3666  It seems that in this sense, perhaps Mewes wou...          0
1980        3398  Rocko's Modern Life: Static Cling was nostalgi...          0
1981        3681  This paean to body positivity and living your ...          0
1982           4  ...surreal, reflective (though never sentiment...          1
1983        5090  One of the most refreshing and enjoyable films...          1
1984       30593  It's hard to imagine anyone not being utterly ...          1
1985         617  This is a journey, troubling and perhaps dange...          1
1986        2117  The pacing lags in multiple areas, but the mys...          1
1987       41837  Heavy-hearted cowboys, wild horses and broken ...          1
1988      380188   Dee Rees' film is a study of historic divisio...          1
1989        3921  It's bloody, it's silly, and it's a gory good ...          0
1990      411374   It's a deeply assured piece of direction, and...          1
1991       44844   Loving is a plaintive reminder of what once was.          1
1992       44340  Two generous helpings of outrageous plot and h...          1
1993        4454  Hale County This Morning, This Evening is a ca...          1
1994      428122   The humor in this movie is based on the conce...          1
1995        1426  Director Ken Loach often examines the lives of...          0
1996        4132  There is much of Tarkovsky's Solaris in the ma...          1
1997       18654  The story unfolds simply, with respect for its...          1
1998       20188  It appears as if even the filmmakers didn't kn...          0
1999      437787   This is not thriller that raises social aware...          0

[2000 rows x 3 columns]

In [277]:
#Get rid off index column 
development_split= pd.DataFrame(development_split, columns = ['Review', 'Freshness'])

In [278]:
development_split.head()

                                              Review  Freshness
0  Even more so than with the other Lecter movies...          0
1   It's a delicious appetizer but you'll crave m...          1
2  'Rim of the World' is a fun adventure flick fi...          1
3  Again, I applaud the effort, but there's reall...          0
4  Might be the least-sexy film about a hedonist ...          0

# Split into positive and negative reviews:

In [336]:
development_split_fresh = development_split[development_split['Freshness'] == 1]
development_split_rotten = development_split[development_split['Freshness'] == 0]
development_split_fresh.head()
development_split_rotten.head()

                                              Review  Freshness
1   It's a delicious appetizer but you'll crave m...          1
2  'Rim of the World' is a fun adventure flick fi...          1
5  ...the obvious passion poured into the film ma...          1
6  Put indelicately via double entendre: The Deat...          1
7   There needs to be a place for teen melodrama....          1

                                               Review  Freshness
0   Even more so than with the other Lecter movies...          0
3   Again, I applaud the effort, but there's reall...          0
4   Might be the least-sexy film about a hedonist ...          0
16   Flunks its most crucial test: the need to pro...          0
17  This is an ugly film. And the only thing uglie...          0

In [337]:
#508 fresh reviews 
development_split_fresh.info()
#492 rotten reviews 
development_split_rotten.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1181 entries, 1 to 1997
Data columns (total 2 columns):
Review       1181 non-null object
Freshness    1181 non-null int64
dtypes: int64(1), object(1)
memory usage: 27.7+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 1999
Data columns (total 2 columns):
Review       819 non-null object
Freshness    819 non-null int64
dtypes: int64(1), object(1)
memory usage: 19.2+ KB

#  1. Word occurancy

## Positive reviews

In [281]:
# Removing punctuation 
def remove_punctuation(dataframe):
    """Remove punctuation from list of tokenized words"""
    new_words = []
    for word in dataframe.Review.str.lower():
        new_word = re.sub(r'[^\w\s]', '', word)
        if new_word != '':
            new_words.append(new_word)
    return new_words

In [282]:
#Remove punctuation from fresh reviews & turn into Series
split_fresh= pd.Series(remove_punctuation(development_split_fresh))
split_fresh.head()

0       its a delicious appetizer but youll crave more
1    rim of the world is a fun adventure flick fill...
2    the obvious passion poured into the film makes...
3    put indelicately via double entendre the death...
4     there needs to be a place for teen melodrama ...
dtype: object

In [283]:
stopWordList = ["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves",\
                "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their",\
                "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was",\
                "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and",\
                "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between",\
                "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off",\
                "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any",\
                "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than",\
                "very", "s", "t", "can", "will", "just", "don", "should", "now"]

In [284]:
#Removing stopwords from fresh

replacements = dict(zip((fr'\b{word}\b' for word in stopWordList), repeat("")))
split_fresh.replace(replacements, regex=True, inplace=True)
split_fresh.replace({r' +': ' ', r' +\.': '.'}, regex=True, inplace=True)

In [285]:
# Lemmatization and Count again
def stem_recount(df):
    import pandas as pd
    # Lemmatization
    from nltk import LancasterStemmer
    st = LancasterStemmer()
    newdf = df.copy()
    for i in range(0,len(df)):
        newdf.iloc[i,0] = st.stem(str(df.iloc[i,0])) 
        # Plz make sure the word column is the first column in df when using this function
    
    # Recount
    duplicate = newdf[newdf.duplicated(['index'])]
    # Plz make sure the 'index' is the column name consisting of words
    for i in range(0,len(newdf)):
        if i >= len(duplicate):
            break
        if newdf.iloc[i,0] == duplicate.iloc[i,0]:
            newdf.iloc[i,1] = newdf.iloc[i,1] + duplicate.iloc[i,1]
    return newdf

In [288]:
new_common_words_fresh_df = common_words_fresh_df.reset_index()

In [289]:
stem_recount(common_words_fresh_df)

            index  Occurence good review
0            film                     89
1            movy                     51
2              on                     51
3           story                     31
4             lik                     29
5              ev                     28
6             fun                     25
7             ful                     24
8            much                     23
9          comedy                     23
10           stil                     21
11            mak                     20
12           ther                     20
13            tim                     20
14            way                     20
15           dram                     17
16           work                     17
17           span                     17
18         doesnt                     17
19         review                     17
20         direct                     17
21            gre                     17
22           good                     17
23           also                     17
24        charact                     17
25          world                     17
26           movy                     17
27         enough                     17
28           best                     16
29      entertain                     16
...           ...                    ...
3714    francisco                      1
3715       jenkin                      1
3716    expertlyc                      1
3717         whal                      1
3718       apolog                      1
3719        swept                      1
3720         dram                      1
3721          off                      1
3722       backst                      1
3723         pred                      1
3724        epoch                      1
3725         cury                      1
3726  wellconceiv                      1
3727        exact                      1
3728         laps                      1
3729          cue                      1
3730       invict                      1
3731       endear                      1
3732         mock                      1
3733        caron                      1
3734        compl                      1
3735        theyd                      1
3736            9                      1
3737          bru                      1
3738      superbl                      1
3739         rest                      1
3740       fletch                      1
3741        sorry                      1
3742        coher                      1
3743        frank                      1

[3744 rows x 2 columns]

In [290]:
#Get most common words in positive reviews 

common_words_fresh = split_fresh.str.split(expand=True).stack().value_counts()
common_words_fresh_df = pd.DataFrame(common_words_fresh)
common_words_fresh_df = common_words_fresh_df.rename({0:'Occurence good review'}, axis='columns')
top_common_words_fresh = common_words_fresh_df[common_words_fresh_df['Occurence good review'] >=3]

In [291]:
top_common_words_fresh

               Occurence good review
film                             185
movie                            121
one                               86
story                             81
like                              78
best                              49
full                              48
time                              45
even                              43
see                               41
review                            40
great                             40
much                              39
new                               39
good                              38
films                             38
way                               38
performances                      38
spanish                           38
fun                               37
enough                            37
make                              37
comedy                            36
never                             33
too                               33
characters                        33
drama                             32
life                              31
doesnt                            31
us                                31
...                              ...
course                             3
subgenre                           3
opportunities                      3
frame                              3
complex                            3
moore                              3
purpose                            3
remain                             3
triumphs                           3
couple                             3
added                              3
vampire                            3
draws                              3
box                                3
accent                             3
tim                                3
german                             3
depiction                          3
nuanced                            3
howard                             3
tells                              3
rolling                            3
absurd                             3
teenage                            3
teenager                           3
kids                               3
oh                                 3
brand                              3
powers                             3
said                               3

[1181 rows x 1 columns]

# Negative reviews

In [292]:
#Remove punctuation from rotten & turn into Series
split_rotten= pd.Series(remove_punctuation(development_split_rotten))
split_rotten.head()

0    even more so than with the other lecter movies...
1    again i applaud the effort but theres really n...
2    might be the leastsexy film about a hedonist e...
3     flunks its most crucial test the need to prop...
4    this is an ugly film and the only thing uglier...
dtype: object

In [293]:
# Removing stopwords from negative reviews
replacements = dict(zip((fr'\b{word}\b' for word in stopWordList), repeat("")))
split_rotten.replace(replacements, regex=True, inplace=True)
split_rotten.replace({r' +': ' ', r' +\.': '.'}, regex=True, inplace=True)

### Lemmatization to compare word occurances differences

In [294]:
# Lemmatization and Count again
def stem_recount(df):
    import pandas as pd
    # Lemmatization
    from nltk import LancasterStemmer
    st = LancasterStemmer()
    newdf = df.copy()
    for i in range(0,len(df)):
        newdf.iloc[i,0] = st.stem(str(df.iloc[i,0])) 
        # Plz make sure the word column is the first column in df when using this function
    
    # Recount
    duplicate = newdf[newdf.duplicated(['index'])]
    # Plz make sure the 'index' is the column name consisting of words
    for i in range(0,len(newdf)):
        if i >= len(duplicate):
            break
        if newdf.iloc[i,0] == duplicate.iloc[i,0]:
            newdf.iloc[i,1] = newdf.iloc[i,1] + duplicate.iloc[i,1]
    return newdf

In [295]:
new_common_words_rotten = split_rotten.str.split(expand=True).stack().value_counts()
new_common_words_rotten_df = pd.DataFrame(new_common_words_rotten).reset_index()

In [296]:
stem_recount(new_common_words_rotten_df)

                       index    0
0                       film  126
1                       movy   93
2                        lik   65
3                         on   56
4                       much   48
5                        too   46
6                      story   43
7                     comedy   40
8                      littl   39
9                         ev   35
10                    enough   34
11                       way   34
12                    doesnt   33
13                   charact   32
14                       ful   31
15                     could   31
16                      good   31
17                       tim   29
18                       mak   29
19                      feel   28
20                    review   28
21                      real   25
22                       bet   24
23                     would   24
24                      plot   23
25                      isnt   22
26                       get   22
27                      span   22
28                       two   21
29                       lif   20
...                      ...  ...
4661                    grim    1
4662                    spar    1
4663                     hoc    1
4664                    jcvd    1
4665                      iv    1
4666                   wacky    1
4667                    offb    1
4668  nameyerhyperselfinvolv    1
4669                   muddl    1
4670                  transp    1
4671                    elit    1
4672                   carey    1
4673                   light    1
4674             circumspect    1
4675                     jag    1
4676                     gun    1
4677                      ar    1
4678                   flail    1
4679                  desult    1
4680                    undo    1
4681                   traum    1
4682                   mirac    1
4683                    falt    1
4684                    grac    1
4685                 landlin    1
4686                    skil    1
4687                      ex    1
4688                     pep    1
4689         straightinstead    1
4690                     lov    1

[4691 rows x 2 columns]

In [297]:
#Get most common words in positive reviews 

common_words_rotten = split_rotten.str.split(expand=True).stack().value_counts()
common_words_rotten_df = pd.DataFrame(common_words_rotten)
common_words_rotten_df = common_words_rotten_df.rename({0:'Occurence bad review'}, axis='columns')
top_common_words_rotten = common_words_rotten_df[common_words_rotten_df['Occurence bad review'] >=3]

In [298]:
top_common_words_rotten

            Occurence bad review
film                         126
movie                         93
like                          65
one                           56
much                          48
too                           46
story                         43
comedy                        40
little                        39
even                          35
enough                        34
way                           34
doesnt                        33
characters                    32
full                          31
could                         31
good                          31
time                          29
make                          29
feels                         28
review                        28
really                        25
better                        24
would                         24
plot                          23
isnt                          22
get                           22
spanish                       22
two                           21
life                          20
...                          ...
teenage                        3
rest                           3
guys                           3
loses                          3
winds                          3
fair                           3
convoluted                     3
please                         3
logic                          3
mark                           3
tragic                         3
grownup                        3
absolutely                     3
revenge                        3
race                           3
thrown                         3
men                            3
leaving                        3
pace                           3
video                          3
word                           3
fear                           3
king                           3
emotions                       3
hero                           3
impressive                     3
emphasis                       3
arent                          3
ground                         3
treatment                      3

[791 rows x 1 columns]

### *** EXPLAIN WHY LEMMATIZATION DOES NOT WORK

# Comparison good and bad movies

In [299]:
#Compare the two lists 
#--> find out which of the words in the good list only appear in the good movies (and not in the bad movies )

In [300]:
#Attempts before 
#outer join --> displays words that are only in good reviews and only in bad reviews
# top_common_words = pd.concat([top_common_words_fresh, top_common_words_rotten], axis=1)
# top_common_words

#inner join 
# top_common_words = pd.merge(top_common_words_fresh, top_common_words_rotten, left_index=True, right_index=True)
# top_common_words

top_fresh_words_exclusive = top_common_words_fresh.merge(top_common_words_rotten, indicator='i', how='outer', left_index=True,\
                                                         right_index=True).query('i == "left_only"').drop('i', 1)

top_rotten_words_exclusive = top_common_words_rotten.merge(top_common_words_fresh, indicator='i', how='outer', left_index=True,\
                                                           right_index=True).query('i == "left_only"').drop('i', 1)

In [301]:
top_fresh_words_exclusive.head()

          Occurence good review  Occurence bad review
20                          3.0                   NaN
2019                        4.0                   NaN
able                        3.0                   NaN
absolute                    4.0                   NaN
accent                      3.0                   NaN

In [302]:
top_rotten_words_exclusive.head()

            Occurence bad review  Occurence good review
100                          3.0                    NaN
3d                           3.0                    NaN
ability                      3.0                    NaN
absolutely                   3.0                    NaN
actress                      3.0                    NaN

In [303]:
#Get only positive words 
top_fresh_words_exclusive_list = top_fresh_words_exclusive['Occurence good review'].index.tolist()
top_fresh_words_exclusive_list

['20',
 '2019',
 'able',
 'absolute',
 'accent',
 'accept',
 'accomplished',
 'account',
 'achievement',
 'acted',
 'added',
 'addition',
 'adult',
 'adventurous',
 'aesthetic',
 'affectionate',
 'age',
 'allowing',
 'allows',
 'alone',
 'ambitious',
 'among',
 'amusing',
 'angry',
 'animated',
 'apart',
 'appreciated',
 'approach',
 'arc',
 'artist',
 'aside',
 'ask',
 'assured',
 'attempts',
 'audacious',
 'authentic',
 'authenticity',
 'awesome',
 'basically',
 'beat',
 'beautifully',
 'beauty',
 'believable',
 'benefits',
 'blast',
 'bleak',
 'blend',
 'blue',
 'blues',
 'body',
 'bond',
 'box',
 'boxing',
 'boy',
 'boys',
 'brain',
 'brand',
 'breaks',
 'breath',
 'brian',
 'brilliant',
 'brilliantly',
 'brings',
 'brisk',
 'british',
 'broken',
 'call',
 'captivating',
 'captures',
 'carter',
 'caught',
 'celebrates',
 'center',
 'central',
 'chamber',
 'change',
 'chaotic',
 'chapter',
 'charismatic',
 'charlie',
 'charm',
 'charming',
 'charms',
 'chase',
 'chicken',
 'childhood',
 'choice',
 'choices',
 'chronicle',
 'cinemas',
 'cinematography',
 'city',
 'clear',
 'clearly',
 'clichés',
 'clift',
 'close',
 'cold',
 'color',
 'combines',
 'comedies',
 'comic',
 'comingofage',
 'comingout',
 'commercial',
 'committed',
 'compelling',
 'complex',
 'concept',
 'concert',
 'conflict',
 'confusion',
 'connection',
 'considered',
 'contemporary',
 'context',
 'control',
 'conventional',
 'convincing',
 'couldnt',
 'couple',
 'course',
 'crafted',
 'craig',
 'crazy',
 'created',
 'creating',
 'creation',
 'creative',
 'creature',
 'crime',
 'crimson',
 'crowdpleaser',
 'crystal',
 'cult',
 'culture',
 'cute',
 'dance',
 'dangerous',
 'david',
 'davis',
 'dc',
 'death',
 'decisions',
 'deep',
 'deeper',
 'deeply',
 'del',
 'delicious',
 'deliciously',
 'delightful',
 'deliver',
 'delivery',
 'demands',
 'depiction',
 'depicts',
 'deserving',
 'design',
 'desire',
 'details',
 'devastating',
 'difficult',
 'dignity',
 'directed',
 'directorial',
 'disney',
 'disturbing',
 'diverting',
 'documentaries',
 'doll',
 'doris',
 'double',
 'dramatic',
 'dramedy',
 'drawn',
 'draws',
 'dreams',
 'due',
 'dynamic',
 'early',
 'eastwood',
 'edge',
 'effective',
 'effectively',
 'elaborate',
 'elephants',
 'elevates',
 'endearing',
 'engrossing',
 'enjoyable',
 'enthralling',
 'entire',
 'epic',
 'episodic',
 'equal',
 'era',
 'essential',
 'event',
 'evil',
 'evocative',
 'examination',
 'examines',
 'exhilarating',
 'experiment',
 'extraordinary',
 'extremely',
 'eye',
 'f',
 'faces',
 'fact',
 'fairly',
 'fan',
 'fare',
 'fascinating',
 'felt',
 'female',
 'fey',
 'fiction',
 'fill',
 'filled',
 'finding',
 'finest',
 'finish',
 'flawed',
 'flaws',
 'flick',
 'focus',
 'focusing',
 'following',
 'footage',
 'foray',
 'force',
 'forces',
 'form',
 'forward',
 'four',
 'frame',
 'frank',
 'frantic',
 'french',
 'friends',
 'friendship',
 'future',
 'gags',
 'gang',
 'general',
 'genuine',
 'george',
 'german',
 'gift',
 'girl',
 'girls',
 'god',
 'gore',
 'gorgeous',
 'grace',
 'grant',
 'greatest',
 'greatness',
 'grief',
 'grim',
 'gripping',
 'gritty',
 'grounded',
 'grows',
 'guts',
 'gwen',
 'hands',
 'harpoon',
 'harrowing',
 'heartbreaking',
 'heartwarming',
 'held',
 'hell',
 'helped',
 'heres',
 'highly',
 'historical',
 'hit',
 'hitch',
 'holds',
 'holiday',
 'honest',
 'horse',
 'howard',
 'hugely',
 'human',
 'humanity',
 'iconic',
 'identify',
 'ignore',
 'ill',
 'imagery',
 'imagine',
 'immediately',
 'importance',
 'impossible',
 'increasingly',
 'incredible',
 'incredibly',
 'industry',
 'inevitable',
 'ingredients',
 'innocence',
 'insightful',
 'insights',
 'inspiring',
 'intelligent',
 'intentions',
 'intrigue',
 'introduction',
 'inventive',
 'involving',
 'irish',
 'irresistibly',
 'jack',
 'jackson',
 'james',
 'jane',
 'jazz',
 'jenkins',
 'job',
 'journey',
 'joy',
 'keeps',
 'kick',
 'kid',
 'knockout',
 'landing',
 'landscape',
 'language',
 'large',
 'last',
 'lasting',
 'late',
 'laugh',
 'launch',
 'lees',
 'lens',
 'lets',
 'lies',
 'light',
 'likeable',
 'liking',
 'list',
 'live',
 'lived',
 'locations',
 'losing',
 'loss',
 'loved',
 'lovers',
 'lucky',
 'machines',
 'magic',
 'male',
 'manages',
 'masculinity',
 'master',
 'masterful',
 'masterpiece',
 'means',
 'memorable',
 'memories',
 'memory',
 'messy',
 'middle',
 'mine',
 'mission',
 'mixing',
 'monsters',
 'mood',
 'moore',
 'mother',
 'move',
 'moving',
 'must',
 'mustsee',
 'natural',
 'nature',
 'necessarily',
 'netflix',
 'netflixs',
 'nevertheless',
 'nice',
 'nicely',
 'night',
 'noir',
 'nonetheless',
 'nonsense',
 'nostalgia',
 'novel',
 'nuanced',
 'number',
 'obsession',
 'odd',
 'odds',
 'odyssey',
 'offbeat',
 'oh',
 'oldfashioned',
 'opening',
 'opportunities',
 'optimism',
 'origins',
 'oscar',
 'otherwise',
 'paced',
 'palma',
 'palpable',
 'panic',
 'parasite',
 'paris',
 'part',
 'pattinson',
 'peak',
 'perfectly',
 'performed',
 'performers',
 'period',
 'person',
 'perspective',
 'perverse',
 'physical',
 'places',
 'playful',
 'pleasure',
 'pleasures',
 'plenty',
 'plus',
 'poem',
 'poignant',
 'police',
 'political',
 'politics',
 'portrayal',
 'possible',
 'power',
 'powerful',
 'powers',
 'precious',
 'presence',
 'presented',
 'primal',
 'primarily',
 'process',
 'production',
 'project',
 'protagonist',
 'provide',
 'provides',
 'provocative',
 'psychological',
 'punch',
 'purpose',
 'puts',
 'questions',
 'quiet',
 'ralph',
 'rare',
 'rarely',
 'realism',
 'realistic',
 'receive',
 'recent',
 'recommend',
 'record',
 'red',
 'references',
 'refreshing',
 'relatable',
 'relationship',
 'relatively',
 'religion',
 'remain',
 'remarkable',
 'remember',
 'reminder',
 'resonate',
 'return',
 'reveals',
 'rich',
 'riot',
 'riveting',
 'rock',
 'role',
 'rolling',
 'romp',
 'room',
 'rooted',
 'run',
 'runtime',
 'sad',
 'said',
 'sake',
 'scares',
 'scene',
 'school',
 'season',
 'second',
 'secrets',
 'secular',
 'sensitive',
 'serves',
 'sets',
 'setup',
 'seventeen',
 'several',
 'sexual',
 'sexuality',
 'sheen',
 'sheer',
 'shock',
 'shocking',
 'shocks',
 'shooting',
 'shot',
 'shots',
 'showcases',
 'side',
 'silliness',
 'simple',
 'sincerity',
 'singular',
 'sinister',
 'sit',
 'sitcom',
 'situation',
 'slice',
 'slightly',
 'slim',
 'smart',
 'snow',
 'society',
 'somewhat',
 'song',
 'songs',
 'soon',
 'soso',
 'sound',
 'space',
 'specific',
 'spiderman',
 'spielberg',
 'spirit',
 'spiritual',
 'splendid',
 'stand',
 'standard',
 'start',
 'state',
 'step',
 'stick',
 'stop',
 'stories',
 'straight',
 'strange',
 'striking',
 'study',
 'stunning',
 'subgenre',
 'successful',
 'suggests',
 'summer',
 'superb',
 'superficial',
 'superhero',
 'supporting',
 'surely',
 'surface',
 'surprisingly',
 'surreal',
 'sweeping',
 'sword',
 'sympathetic',
 'talent',
 'talented',
 'tales',
 'talking',
 'technical',
 'teenager',
 'telling',
 'tells',
 'tense',
 'terms',
 'terrific',
 'terrifying',
 'thankfully',
 'theme',
 'themes',
 'thomas',
 'three',
 'thrillers',
 'thrilling',
 'tim',
 'timely',
 'told',
 'tom',
 'totally',
 'touch',
 'touches',
 'touching',
 'tough',
 'towards',
 'toxic',
 'traditional',
 'tragedy',
 'transcendent',
 'transcends',
 'trauma',
 'treat',
 'tribute',
 'triumphs',
 'trust',
 'truth',
 'turing',
 'tv',
 'twists',
 'type',
 'uncanny',
 'uncomfortable',
 'undemanding',
 'undeniably',
 'understanding',
 'understated',
 'unexpected',
 'universal',
 'universe',
 'urban',
 'used',
 'uses',
 'vampire',
 'vibrant',
 'viewer',
 'visceral',
 'voice',
 'warm',
 'wasnt',
 'watchable',
 'watson',
 'weird',
 'wildly',
 'william',
 'williams',
 'willingness',
 'winner',
 'winning',
 'wit',
 'witty',
 'wonderful',
 'wonderfully',
 'woodstock',
 'words',
 'worked',
 'worlds',
 'worthwhile',
 'written',
 'wrong',
 'york',
 'youth']

In [304]:
#take out the ones that seem to make sense: 
top_fresh_words_exclusive = ['beautiful',
 'best',
 'comic',
 'compelling',
 'emotional',
 'entertaining',
 'family',
 'fans',
 'fun',
 'game',
 'high',
 'humor',
 'kind',
 'new',
 'powerful',
 'satisfying',
 'script',
 'simple',
 'true']

top_fresh_words_exclusive

['beautiful',
 'best',
 'comic',
 'compelling',
 'emotional',
 'entertaining',
 'family',
 'fans',
 'fun',
 'game',
 'high',
 'humor',
 'kind',
 'new',
 'powerful',
 'satisfying',
 'script',
 'simple',
 'true']

In [305]:
#Get only negative words 
top_rotten_words_exclusive_list = top_rotten_words_exclusive['Occurence bad review'].index.tolist()
top_rotten_words_exclusive_list

['100',
 '3d',
 'ability',
 'absolutely',
 'actress',
 'add',
 'adds',
 'affair',
 'aim',
 'aiming',
 'appealing',
 'appears',
 'attempt',
 'attention',
 'author',
 'awkward',
 'badly',
 'bag',
 'barely',
 'basic',
 'beginning',
 'bigger',
 'biggest',
 'blank',
 'bore',
 'bored',
 'boring',
 'brooks',
 'came',
 'camera',
 'campy',
 'care',
 'cause',
 'charmless',
 'cheesy',
 'children',
 'christopher',
 'cliche',
 'cliches',
 'cling',
 'clint',
 'clumsy',
 'collection',
 'colossal',
 'commentary',
 'competent',
 'connect',
 'continually',
 'continues',
 'contrivance',
 'contrived',
 'convoluted',
 'cool',
 'corny',
 'corporate',
 'crisis',
 'decent',
 'decided',
 'detail',
 'devoid',
 'disappointingly',
 'disappointment',
 'divine',
 'drab',
 'dumb',
 'earnest',
 'eastwoods',
 'effort',
 'emphasis',
 'endeavor',
 'ends',
 'engage',
 'engaged',
 'equally',
 'equivalent',
 'escape',
 'execution',
 'exercise',
 'extreme',
 'fails',
 'fair',
 'fantastic',
 'fear',
 'featurelength',
 'features',
 'fight',
 'five',
 'flat',
 'flight',
 'formula',
 'formulaic',
 'front',
 'fury',
 'generic',
 'giant',
 'golf',
 'gooding',
 'goofy',
 'grab',
 'grand',
 'grisly',
 'grownup',
 'guy',
 'guys',
 'hair',
 'halfbaked',
 'hand',
 'handful',
 'happens',
 'hardly',
 'heads',
 'heist',
 'hold',
 'hollow',
 'hour',
 'humour',
 'ian',
 'identity',
 'imagination',
 'installment',
 'instead',
 'intriguing',
 'key',
 'lacking',
 'latest',
 'leaving',
 'legend',
 'letdown',
 'lifeless',
 'lightweight',
 'likable',
 'listen',
 'living',
 'logic',
 'loses',
 'lukewarm',
 'madness',
 'manipulative',
 'marketing',
 'matt',
 'meant',
 'mental',
 'mess',
 'misses',
 'mixed',
 'money',
 'neither',
 'nick',
 'nobody',
 'none',
 'nonsensical',
 'nowhere',
 'nuclear',
 'occasionally',
 'offensive',
 'offer',
 'opera',
 'opportunity',
 'order',
 'pacing',
 'painfully',
 'park',
 'particularly',
 'paul',
 'pay',
 'pictures',
 'pieces',
 'plagued',
 'please',
 'poor',
 'possibly',
 'potential',
 'pretentious',
 'previous',
 'problem',
 'problems',
 'promising',
 'props',
 'prove',
 'quickly',
 'race',
 'raunchy',
 'reach',
 'read',
 'redemption',
 'repeatedly',
 'richard',
 'rockos',
 'routine',
 'runs',
 'sappy',
 'saving',
 'secret',
 'sentiment',
 'shaky',
 'shallow',
 'shame',
 'shes',
 'showcase',
 'showing',
 'single',
 'slasher',
 'slog',
 'soap',
 'somehow',
 'son',
 'sounds',
 'soundtrack',
 'speak',
 'spectacle',
 'spectacular',
 'spite',
 'starts',
 'stay',
 'steam',
 'steps',
 'storyline',
 'stronger',
 'struggles',
 'stuck',
 'stunts',
 'stupid',
 'substance',
 'suffers',
 'superman',
 'supposed',
 'suspect',
 'talk',
 'tedious',
 'tension',
 'tepid',
 'terrible',
 'test',
 'textbook',
 'thin',
 'thinking',
 'thought',
 'thrills',
 'thrown',
 'tired',
 'total',
 'toys',
 'trapped',
 'treatment',
 'tries',
 'ugly',
 'unique',
 'unless',
 'unlikely',
 'unoriginal',
 'unusual',
 'vanity',
 'vapid',
 'variety',
 'video',
 'visuals',
 'wacky',
 'wannabe',
 'wars',
 'weak',
 'wearing',
 'west',
 'whos',
 'winds',
 'wish',
 'working',
 'worse',
 'worst',
 'writers',
 'zombie']

In [306]:
#take out the ones that seem to make sense: 
top_rotten_words_exclusive = [
 'bad',
 'big',
 'dead',
 'hard',
 'interesting',
 'jokes',
 'latest',
 'less',
 'lot',
 'part',
 'plot',
 'probably',
 'seem',
 'seems',
 'simply',
 'think',
 'tries',
 'ultimately',
 'violence',
 'want',
 'would',
 'yet']

In [307]:
top_rotten_words_exclusive

['bad',
 'big',
 'dead',
 'hard',
 'interesting',
 'jokes',
 'latest',
 'less',
 'lot',
 'part',
 'plot',
 'probably',
 'seem',
 'seems',
 'simply',
 'think',
 'tries',
 'ultimately',
 'violence',
 'want',
 'would',
 'yet']

## Labeling functions

### A. Good / bad exclusive words occurrences

In [308]:
ABSTAIN = -1
NOTFRESH = 0
FRESH = 1

@labeling_function()

def fresh(x):
    for word in top_fresh_words_exclusive:
        if word in str(x).lower():
            return FRESH
    return ABSTAIN
#return FRESH if "best" in x.str.lower() else ABSTAIN

In [309]:
lfs = [fresh]

applier = PandasLFApplier(lfs=lfs)
sample_L = applier.apply(development_split)

100%|██████████| 2000/2000 [00:10<00:00, 185.59it/s]

In [310]:
sample_L

array([[-1],
       [-1],
       [ 1],
       ...,
       [-1],
       [-1],
       [-1]])

In [311]:
coverage_fresh = (sample_L != ABSTAIN).mean(axis=0)
print("good coverage:{:.1%}".format(coverage_fresh[0]))

good coverage:9.8%

In [312]:
pd.set_option('display.expand_frame_repr', False)

In [313]:
LFAnalysis(L=sample_L, lfs=lfs).lf_summary()

       j Polarity  Coverage  Overlaps  Conflicts
fresh  0      [1]    0.0985       0.0        0.0

In [314]:
#same for rotten: 

ABSTAIN = -1
NOTFRESH = 0
FRESH = 1

@labeling_function()
def rotten(x):
    for word in top_rotten_words_exclusive:
        if word in str(x).lower():
            return NOTFRESH
    return ABSTAIN
#return FRESH if "best" in x.str.lower() else ABSTAIN

In [315]:
lfs = [rotten]

applier = PandasLFApplier(lfs=lfs)
sample_L = applier.apply(development_split)

100%|██████████| 2000/2000 [00:12<00:00, 161.22it/s]

In [316]:
coverage_rotten = (sample_L != ABSTAIN).mean(axis=0)
print("rotten coverage:{:.1%}".format(coverage_rotten[0]))

rotten coverage:11.6%

### B. Word 'too' occurances

In [317]:
common_words_fresh_df[common_words_fresh_df.index == 'too']

     Occurence good review
too                     33

In [318]:
common_words_rotten_df[common_words_rotten_df.index == 'too']

     Occurence bad review
too                    46

### C. Word 'far' occurrences

In [319]:
common_words_fresh_df[common_words_fresh_df.index == 'far']

     Occurence good review
far                     17

In [320]:
common_words_rotten_df[common_words_rotten_df.index == 'far']

     Occurence bad review
far                    10

### D. "n't" words occurrences

In [321]:
# Word occurancy that with punctuation with it

# Word occurrences dataframe for fresh reviews
development_split_fresh_1 = development_split_fresh_series.str.split(expand=True).stack().value_counts()
development_split_fresh_df = pd.DataFrame(development_split_fresh_1).reset_index()

# Words occurrences dataframe for rotten reviews
development_split_rotten_1 = development_split_rotten_series.str.split(expand=True).stack().value_counts()
development_split_rotten_df = pd.DataFrame(development_split_rotten_1).reset_index()

### E. Capital words occurrences

In [343]:
fresh_df

                                                 Review
1      It's a delicious appetizer but you'll crave m...
2     'Rim of the World' is a fun adventure flick fi...
5     ...the obvious passion poured into the film ma...
6     Put indelicately via double entendre: The Deat...
7      There needs to be a place for teen melodrama....
8     Riveting entertainment thanks to its three lea...
9                [T]his is undeniably great filmmaking.
10    Chicken Run isn't just chock-full of reference...
11    Yet another adult comedy that's heavy with rau...
12    Netflix's Bikram documentary gets even more di...
13    Finishing with a fine flourish makes this slow...
14    Sure, it has its precious moments -- but Hitch...
15    Dumbo is a lot of work by a lot of talented pe...
18     It has all the ingredients for cult immortali...
21     Ferrara gives a nice flow to this far-from-ni...
22    It's difficult to watch a film that doesn't st...
23    Call me. I'll see it again with you this weekend.
24    The characters are fully dimensional, the perf...
25     The Oscar-nominated documentary 20 Feet From ...
26           There is nothing more to say, except 'Go.'
28     A very subtle and smooth film. Basically a Eu...
30    A queer teen love story told through the lens ...
31    ...while Jackson has his moments on the hardwo...
32              There's nary a dull moment in the film.
35    This is a film principally about self-protecti...
36     Bottle Shock is a feel good movie in the best...
37    The film walks a fine line here, delivering en...
39    All the jokes land, and for most of its runtim...
40       Unashamed of flaunting its B-movie conventions
41    Though it never ventures past the tourist quar...
...                                                 ...
1948  Moore was always bigger-than-life and that's h...
1949  Body at Brighton Rock is the kind of movie tha...
1953                      A film you will never forget.
1954  The movie is fun, largely because it proposes ...
1955   The Incredibles 2 makes its mark as a thrilli...
1956  "Echo in the Canyon" works more as a fond trib...
1958   You'll feel the cold on the Hoth-like ice pla...
1959  Enter the Florpus picks up pretty much where t...
1960  [An] admirable distillation of a tough subject...
1961  Likeable documentary that serves as a fascinat...
1962  The lack of nuance with which patriarchy and h...
1966   A movie that approaches the level of great bo...
1972  The film succeeds as a deeply involving study ...
1976  Putting the middle finger to originality, narr...
1977   L.A. Confidential understands that men don't ...
1978  Ignoring the weak storyline entirely, Rango is...
1982  ...surreal, reflective (though never sentiment...
1983  One of the most refreshing and enjoyable films...
1984  It's hard to imagine anyone not being utterly ...
1985  This is a journey, troubling and perhaps dange...
1986  The pacing lags in multiple areas, but the mys...
1987  Heavy-hearted cowboys, wild horses and broken ...
1988   Dee Rees' film is a study of historic divisio...
1990   It's a deeply assured piece of direction, and...
1991   Loving is a plaintive reminder of what once was.
1992  Two generous helpings of outrageous plot and h...
1993  Hale County This Morning, This Evening is a ca...
1994   The humor in this movie is based on the conce...
1996  There is much of Tarkovsky's Solaris in the ma...
1997  The story unfolds simply, with respect for its...

[1181 rows x 1 columns]

In [377]:
# Define function to remove punctuation
def remove_punctuation_capital_letters(dataframe):
    new_words = []
    for word in dataframe.Review:
        new_word = re.sub(r'[^\w\s]', '', word)
        if new_word != '':
            new_words.append(new_word)
    return new_words

In [379]:
# Removing punctuation in reviews
fresh_df = pd.DataFrame(pd.Series(remove_punctuation_capital_letters(development_split_fresh))\
                        .str.split(expand=True).stack().value_counts()) # Split review into words

# Capital letters words that are more than 1 character
fresh_capital_letters = [word for word in fresh_df.index if word.isupper() and len(word)>1]
len(fresh_capital_letters)

26

In [382]:
# Removing punctuation in reviews
rotten_df = pd.DataFrame(pd.Series(remove_punctuation_capital_letters(development_split_rotten))\
                        .str.split(expand=True).stack().value_counts()) # Split review into words

# Capital letters words that are more than 1 character
rotten_capital_letters = [word for word in rotten_df.index if word.isupper() and len(word)>1]
len(rotten_capital_letters)

30

# 2. Punctuation occurancy

In [326]:
# Turn review column into Series
development_split_fresh_series = pd.Series(development_split_fresh.Review)
development_split_rotten_series = pd.Series(development_split_rotten.Review)

In [327]:
# Positive reviews
# Split reviews into word
fresh_split = pd.Series(development_split_fresh_series.str.split(expand=True).stack())
fresh_words = [i for i in fresh_split]

# Split words into characters
def split_str():
    return [list(ch) for ch in fresh_words]
fresh_split_words = pd.Series(split_str())

In [328]:
# Negative reviews
# Split reviews into word
rotten_split = pd.Series(development_split_rotten_series.str.split(expand=True).stack())
rotten_words = [i for i in rotten_split]

# Split words into characters
def split_str():
    return [list(ch) for ch in rotten_words]
rotten_split_words = pd.Series(split_str())

In [329]:
# Turn into a flattened list
fresh_flattened_list = [y for x in fresh_split_words for y in x]
rotten_flattened_list = [y for x in rotten_split_words for y in x]

# Count the occurancy of each character
# Positive reviews
fresh_split_characters = pd.Series(fresh_flattened_list).value_counts()
fresh_split_characters = pd.DataFrame(fresh_split_characters).reset_index()

# Negative reviews
rotten_split_characters = pd.Series(rotten_flattened_list).value_counts()
rotten_split_characters = pd.DataFrame(rotten_split_characters).reset_index()

### A. Question mark occurrences

In [330]:
# Count the # of occurance of '?' in fresh reviews
fresh_split_characters[fresh_split_characters['index'] == '?']

   index   0
65     ?  13

In [331]:
# Count the # of occurance of '?' in rotten reviews
rotten_split_characters[rotten_split_characters['index'] == '?']

   index   0
55     ?  25

In [332]:
list_with_question_mark = []
for review in development_split_rotten.Review:
    if '?' in review:
        list_with_question_mark.append(review)
        
print (list_with_question_mark[:3])

[" Oh god, have I ever seen a more tedious 'erotic' movie than this one?", " I found myself thinking horrid, unspeakable thoughts during the screening. Thoughts like, 'come back Joel Schumacher, all is forgiven!' and 'maybe David Hasselhoff's Nick Fury wasn't so bad.' What kind of superhero movie DOES THAT to a man?", "Why did Jarmusch pick a zombie film? That's possibly a question that will pop up on most viewers' minds, especially Jarmusch devotees, and for the first two thirds of the film it does seem like the director wants to have a bit fun with the genre."]

### B. Exclaimation mark occurrences

In [333]:
# Count the # of occurance of '!' in fresh reviews
fresh_split_characters[fresh_split_characters['index'] == '!']

   index  0
68     !  9

In [334]:
# Count the # of occurance of '!' in fresh reviews
rotten_split_characters[rotten_split_characters['index'] == '!']

   index  0
69     !  7